name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: eks-repository
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update image tag in Kubernetes files
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: eks-repository
          IMAGE_TAG: latest
        run: |
          sed "s|appimage|$REGISTRY/$REPOSITORY:$IMAGE_TAG|g" app/k8s/deployment.yaml > temp.yaml
          rm app/k8s/deployment.yaml
          mv temp.yaml app/k8s/deployment.yaml
          cat app/k8s/deployment.yaml

      - name: Update KubeConfig and Deploy to Kubernetes
        run: |
          aws eks update-kubeconfig --name eks-cluster
          kubectl apply -f app/k8s/deployment.yaml -n default
