aws_region          = "us-east-1"
vpc_name            = "eks-vpc"
vpc_cidr            = "10.0.0.0/16"
availability_zones  = ["us-east-1a", "us-east-1b"]
public_subnets      = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets     = ["10.0.3.0/24", "10.0.4.0/24"]
cluster_name        = "eks-cluster"
eks_version         = "1.28"
node_group_size     = 2
node_group_min_size = 1
node_group_max_size = 3
node_instance_type  = "t3.medium"
alb_name            = "eks-alb"
alb_internal        = false
